### ISSUE TITLE
Problem installing dependencies.

### ISSUE THREAD

**Issue by fvbatistoni** [coliff/bootstrap-5-migrate-tool#67]
When I put npm install it gives me a lot of dependencies deprecated. One dependency does not work because subdependencies does not works too.... Can you fix it?

**Comment by coliff** [comment]
Gulp v4 (which this project uses) hasn't [been updated since 2019](https://github.com/gulpjs/gulp/releases) and it does use some deprecated dependencies. You can ignore those warnings though and still use the project.

I've tested it with Node v16, v18 and v20 and it works as expected.

![image](https://github.com/coliff/bootstrap-5-migrate-tool/assets/1212885/94c35a35-a98b-4fe9-8f29-7d975abd3924)

**Comment by fvbatistoni** [comment]
glob-parent  <5.1.2
Severity: high
glob-parent vulnerable to Regular Expression Denial of Service in enclosure regex - https://github.com/advisories/GHSA-ww39-953v-wcq6
fix available via `npm audit fix --force`
Will install gulp@3.9.1, which is a breaking change
node_modules/glob-watcher/node_modules/glob-parent
node_modules/gulp/node_modules/glob-parent
  chokidar  1.0.0-rc1 - 2.1.8
  Depends on vulnerable versions of glob-parent
  node_modules/glob-watcher/node_modules/chokidar
    glob-watcher  3.0.0 - 5.0.5
    Depends on vulnerable versions of chokidar
    node_modules/glob-watcher
      gulp  >=4.0.0
      Depends on vulnerable versions of glob-watcher
      Depends on vulnerable versions of vinyl-fs
      node_modules/gulp
  glob-stream  5.3.0 - 6.1.0
  Depends on vulnerable versions of glob-parent
  node_modules/gulp/node_modules/glob-stream
    vinyl-fs  2.4.2 - 3.0.3
    Depends on vulnerable versions of glob-stream
    node_modules/gulp/node_modules/vinyl-fs

**Comment by fvbatistoni** [comment]
this is my problem. 
There is no problem? It will work fine?

**Comment by coliff** [comment]
Great! Glad you got it working. Yes, I have a Node script which can take a bunch of SVGs and create PNG images. Is that what you need? If so I'll create a quick GitHub repo for you tomorrow if you like.

Thanks for the ☕ 👍
