### ISSUE TITLE
Are recursive replacements on the roadmap?

### ISSUE THREAD

**Issue by thiagolvlsantos** [coliff/bootstrap-5-migrate-tool#68]
Hi @coliff,

Firstly, I would like to thank you for doing this project. Secondly, I`ve been trying to find a tool to migrate BS4 to BS5 and this project looked interesting, but the restriction of a flat source directory seems to be too restrictive.

Do you have plans to make replacement recursively? I mean for every file and directory under '/src' perform a deep search replacement. I think this adjust would make your tool more popular and usefull, for me at least :) Most developers have this use case.

As a humble suggestion, if you parametrize the .js to receive in/out directories, I could just make a 'find' based bash script to scan all directories. I dont know how easy/hard is doing it in gulp scripts :) But I`ll try while you dont answer ;)

Best regards,

Thiago

**Comment by coliff** [comment]
Thanks for the message and suggestion. I agree that the script could be more useful if it allowed for that.

I saw that someone had forked this project (https://github.com/EdRW/bootstrap-5-migrate-tool/commit/d7829a5ce833f68176424422886db73560164f83) and added some config options- including for specifying the input and output directory. I think having that functionality would be great.

**Comment by Disane87** [comment]
I added this functionality in #74 because I needed it urgently in a company project with more than 300 files to search in.

**Comment by coliff** [comment]
Thanks for that PR @Disane87 ! 🥇
