### ISSUE TITLE
Is it working

### ISSUE THREAD

**Issue by Yusriaja** [coliff/bootstrap-5-migrate-tool#88]
I've tried many times, not even 1 BS 4 class been changed

**Comment by coliff** [comment]
Yes it is working. I can see the results of the test run on GitHub Actions here:
https://github.com/coliff/bootstrap-5-migrate-tool/actions/runs/9055330473/job/24876296497#logs

![image](https://github.com/coliff/bootstrap-5-migrate-tool/assets/1212885/0ed8b644-5fde-49d3-ae16-28ed51acf238)

If you're having issues double check all your file-paths and/or try the different options.

**Comment by neerdoc** [comment]
It only works in sub folders. I also tried many times without any changes or warnings using a folder next to the working folder. Then I tried linking it and it worked perfectly.

So, this **_does not_** work:
`npx gulp migrate --overwrite --verbose --src ../my_project/`

This **_does_** work:
```
ln -s ../my_project
npx gulp migrate --overwrite --verbose --src ./my_project/
```

**Comment by coliff** [comment]
> It only works in sub folders.

Yes, I think that's expected. searching and replacing backwards across your entire HD/SSD could be very dangerous if you mistype a directory path! I'll take a look at possibly making a mention of this in the README though.
