### ISSUE TITLE
`.close` to `.btn-close` regex needs adjustment

### ISSUE THREAD

**Issue by bdanchilla** [coliff/bootstrap-5-migrate-tool#91]
`.foobar-close` will result in `.foobar-btn-close`

`.close-bz` will result in `.btn-close-bz`

Rerunning the script will compound these issues:

eg)
` .foobar-btn-btn-close`, `.btn-btn-close-bz` and if rerun
` .foobar-btn-btn-btn-close`, `.btn-btn-btn-close-bz`

Very useful tool though! Thanks for creating.

**Comment by coliff** [comment]
Thanks for the feedback and reporting that issue. I’ll look to see if I can get that fixed today.
